### ISSUE TITLE
Could not find path to game

### ISSUE THREAD

**Issue by VandalQrow** [aEnigmatic/xcom2-launcher#23]
Could not find a part of the path 'C:\Users\andre\OneDrive\Documents\my games\XCOM2\XComGame\Config\XComEngine.ini'.
Stack:
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize, Boolean checkHost)
   at System.IO.StreamReader..ctor(String path, Encoding encoding)
   at System.IO.File.ReadLines(String path)
   at XCOM2Launcher.XCOM.XCOM2.DetectModDirs()
   at XCOM2Launcher.Program.InitializeSettings()
   at XCOM2Launcher.Program.Main()

**Comment by aEnigmatic** [comment]
Hey, you can find the active repo for the mod launcher under https://github.com/X2CommunityCore/xcom2-launcher
